# Generated by Django 2.2.25 on 2021-12-16 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysocialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='image_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='mysocialapp.PostLikes'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='tag',
            field=models.ManyToManyField(related_name='post_tag', to='mysocialapp.AddTag'),
        ),
        migrations.AlterField(
            model_name='postlikes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='image_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='mysocialapp.PostLikes'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_response', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertagweitage',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_tag', to='mysocialapp.AddTag'),
        ),
        migrations.AlterField(
            model_name='usertagweitage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
